# BMAD Create Architecture — Copilot Playbook Generator
name: bmad-create-architecture-copilot
description: "Generates a Copilot playbook for the 8-step collaborative architecture decision workflow"
author: "BMad"

# This workflow does NOT execute architecture decisions.
# It generates a markdown playbook with copy-paste prompts for Copilot Chat.
ecc_orchestration:
  enabled: false
  reason: "This workflow generates a document — it does not execute decisions"

output:
  format: "markdown"
  file_pattern: "copilot-playbook-architecture.md"
  output_dir: "{project-root}/_bmad-output/implementation-artifacts"

# Project Knowledge — same sources as original workflow
project_knowledge:
  enabled: true
  load_at_session_start: true
  files:
    required:
      - "{project-root}/_bmad-output/planning-artifacts/prd.md"
    optional:
      - "{project-root}/_bmad-output/planning-artifacts/archie-ux-playground.html"
      - "{project-root}/docs/brainstorming/*.md"

config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
planning_artifacts: "{output_folder}/planning-artifacts"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

installed_path: "{project-root}/_ecc/workflows/bmad-create-architecture-copilot"
instructions: "{installed_path}/instructions.xml"

standalone: true
