import parData from "@/data/challengePar.generated.json"

/**
 * Reference "par" for a challenge (LX3, D74): the lean reference build's monthly cost ($) + node
 * count — the achievable benchmark the results modal shows after 3★ so a learner can tell a lean
 * clear from a wasteful one. Generated by `tests/integration/challenges/challengePar.test.ts`
 * (`UPDATE_PAR=1`) and kept fresh as part of the D75 re-calibration exit gate.
 */
export interface ChallengePar {
  /** Monthly cost ($) of the lean reference build. */
  cost: number
  /** Node count of the lean reference build. */
  nodes: number
}

const PAR = parData as Record<string, ChallengePar>

/** Par benchmark for a challenge id, or undefined when none was generated. */
export function getChallengePar(id: string): ChallengePar | undefined {
  return PAR[id]
}
