import generated from "@/data/challengeBreakDials.generated.json"
import { BREAK_ATTRIBUTES, type BreakAttribute } from "@/engine/breakDetection"

/**
 * Quest-level collectible break dials (owner decision 2026-06-11): how many Experts a quest's
 * break challenge can pay = which dials can fell its LEAN reference build. Generated by the
 * breakDials harness (freshness-gated, UPDATE_BREAK_DIALS=1 regenerates); single-source quests
 * only — multi-source / unknown ids fall back to the full set (legacy economy).
 */
const DIALS: Readonly<Record<string, readonly string[]>> = generated

export function questBreakDials(challengeId: string): readonly BreakAttribute[] {
  const entry = DIALS[challengeId]
  if (!entry) return BREAK_ATTRIBUTES
  return BREAK_ATTRIBUTES.filter((a) => entry.includes(a))
}
