/**
 * Pixel-art component icons (generated via PixelLab, stored in `public/icons/<id>.png`).
 *
 * The icon filename matches the component id, so the URL is derived — no per-component data/schema
 * change. We gate on a known id set (not the raw id) so a missing/typo'd id falls back to the
 * category icon instead of a broken <img>, and because the URL is a same-origin relative path there
 * is no external-URL injection surface (unlike the original `logoUrl` idea — see D37).
 *
 * Keep COMPONENT_ICON_IDS in lockstep with the files in public/icons/ — the consistency test
 * `tests/unit/lib/componentIcons.test.ts` fails if they drift.
 */
export const COMPONENT_ICON_IDS: ReadonlySet<string> = new Set([
  "ably",
  "adyen",
  "airflow",
  "algolia",
  "amazon-mq",
  "anthropic",
  "api-client",
  "arangodb",
  "auth0",
  "aws-alb",
  "aws-api-gateway",
  "aws-aurora",
  "aws-bedrock",
  "aws-kinesis",
  "aws-lambda",
  "aws-s3",
  "aws-sqs",
  "bullmq",
  "celery",
  "cloudflare-cdn",
  "cloudflare-dns",
  "cloudflare-waf",
  "cloudflare-workers",
  "cloudfront",
  "cockroachdb",
  "data-lake",
  "datadog",
  "dbt",
  "dotnet",
  "dynamodb",
  "elasticsearch",
  "envoy",
  "etl-pipeline",
  "fastly-cdn",
  "fivetran",
  "flink",
  "gcp-pubsub",
  "gcs",
  "go-service",
  "grafana",
  "graph-db",
  "haproxy",
  "influxdb",
  "iot-sensors",
  "kafka",
  "keycloak",
  "kong",
  "laravel",
  "llm-gateway",
  "memcached",
  "minio",
  "mobile-users",
  "mongodb",
  "mysql",
  "nats",
  "neo4j",
  "neptune",
  "newrelic",
  "nginx",
  "node-express",
  "openai",
  "payment-gateway",
  "paypal",
  "pinecone",
  "postgresql",
  "prometheus",
  "pusher",
  "python-django",
  "python-fastapi",
  "python-flask",
  "qdrant",
  "rabbitmq",
  "rails",
  "rate-limiter",
  "redis",
  "redis-cache",
  "redpanda",
  "route53",
  "serverless",
  "siem",
  "socketio",
  "spark-streaming",
  "splunk",
  "spring-boot",
  "stripe",
  "timescaledb",
  "vault",
  "vector-db",
  "weaviate",
  "web-users",
  "websocket-server",
])

/** Returns the relative icon URL for a component id, or null when no pixel icon exists for it. */
export function getComponentIconUrl(componentId: string): string | null {
  return COMPONENT_ICON_IDS.has(componentId) ? `/icons/${componentId}.png` : null
}
