import { describe, it, expect } from "vitest"
import { readFileSync, readdirSync } from "node:fs"
import { resolve, join } from "node:path"
import { load } from "js-yaml"

/**
 * B2 drift gate (Kane QA, 2026-06-15): the AI-prompt template MUST stay in lockstep with the
 * component library + schema version. Hand-maintenance let it rot to schema 1.0.0 + 10/114
 * components. These tests fail the build the moment the committed template drifts from the
 * generator's output — forcing `npx tsx scripts/gen-prompt-template.ts` before merge.
 */

const ROOT = resolve(__dirname, "..", "..", "..")
const TEMPLATE = join(ROOT, "src", "data", "prompt-template.md")
const COMPONENTS_DIR = join(ROOT, "src", "data", "components")
const SCHEMA_FILE = join(ROOT, "src", "schemas", "architectureFileSchema.ts")

interface ComponentYaml {
  id: string
  config_variants?: { id: string }[]
}

function loadLibrary(): Map<string, Set<string>> {
  const map = new Map<string, Set<string>>()
  for (const f of readdirSync(COMPONENTS_DIR).filter((f) => f.endsWith(".yaml"))) {
    const c = load(readFileSync(join(COMPONENTS_DIR, f), "utf8")) as ComponentYaml
    if (!c?.id) continue
    map.set(c.id, new Set((c.config_variants ?? []).map((v) => v.id)))
  }
  return map
}

function schemaVersion(): string {
  return readFileSync(SCHEMA_FILE, "utf8").match(/CURRENT_SCHEMA_VERSION\s*=\s*"([^"]+)"/)![1]
}

const template = readFileSync(TEMPLATE, "utf8")
const library = loadLibrary()

describe("prompt-template.md drift gate (B2)", () => {
  it("declares the CURRENT schema version", () => {
    expect(template).toContain(`schema_version\` must be \`"${schemaVersion()}"\``)
  })

  it("lists EVERY component in the library (no missing IDs)", () => {
    const listed = new Set([...template.matchAll(/^\| `([a-z0-9-]+)` \|/gm)].map((m) => m[1]))
    const missing = [...library.keys()].filter((id) => !listed.has(id))
    expect(missing, `template is missing components: ${missing.join(", ")}`).toEqual([])
  })

  it("lists ONLY real component IDs (no stale/removed IDs)", () => {
    const listed = [...template.matchAll(/^\| `([a-z0-9-]+)` \|/gm)].map((m) => m[1])
    const stale = listed.filter((id) => !library.has(id))
    expect(stale, `template lists non-existent components: ${stale.join(", ")}`).toEqual([])
  })

  it("the embedded example uses only real component/variant pairs and imports clean", () => {
    const blocks = [...template.matchAll(/```yaml\n([\s\S]*?)```/g)].map((m) => m[1])
    const example = load(blocks[blocks.length - 1]) as {
      schema_version: string
      nodes: { component_id: string; config_variant_id?: string }[]
    }
    expect(example.schema_version).toBe(schemaVersion())
    for (const n of example.nodes) {
      const variants = library.get(n.component_id)
      expect(variants, `example uses unknown component ${n.component_id}`).toBeDefined()
      if (n.config_variant_id) {
        expect(
          variants!.has(n.config_variant_id),
          `example uses unknown variant ${n.component_id}/${n.config_variant_id}`,
        ).toBe(true)
      }
    }
  })

  it("is marked auto-generated (so no one hand-edits it)", () => {
    expect(template).toContain("AUTO-GENERATED by scripts/gen-prompt-template.ts")
  })
})
