import { describe, it, expect, beforeAll, vi } from "vitest"
import { writeFileSync, mkdirSync } from "node:fs"
import { join } from "node:path"
import { dump } from "js-yaml"

const { mockComponentRepo, emptyRepo } = vi.hoisted(() => ({
  mockComponentRepo: { getAll: vi.fn(), getById: vi.fn(), getByCategory: vi.fn() },
  emptyRepo: { getAll: vi.fn() },
}))
vi.mock("@/repositories/componentRepository", () => ({ componentRepository: mockComponentRepo }))
vi.mock("@/repositories/stackRepository", () => ({ stackRepository: emptyRepo }))
vi.mock("@/repositories/blueprintRepository", () => ({ blueprintRepository: emptyRepo }))
vi.mock("@/repositories/metricCategoryRepository", () => ({ metricCategoryRepository: emptyRepo }))
vi.mock("@/lib/firebase", () => ({ auth: { currentUser: null }, db: {} }))

import { getAllChallenges } from "@/services/challengeLoader"
import { componentLibrary } from "@/services/componentLibrary"
import { MAX_REPLICAS } from "@/lib/constants"
import { loadLocalComponents, challengeCurve, buildClearingSolution, scoreSolution, toArchitectureFixture } from "./referenceSolution"

/**
 * Tier-6 absurd capstone completion proof (D71).
 *
 * Every capstone is completable by a player within the UI's real build budget (≤50 nodes,
 * ≤20 replicas/node). For each, this builds the reference solution, caps replicas at MAX_REPLICAS
 * (the architecture-import + stepper ceiling), runs the REAL sim + scorer, and asserts it CLEARS
 * (≥1★). This is the deterministic backbone of the proof; the capstone E2E then drives the same
 * fixtures through the real UI and screenshots a passing result.
 *
 * Run with GEN_CAPSTONE_FIXTURES=1 to (re)write the E2E fixtures + the human-readable proof report:
 *   GEN_CAPSTONE_FIXTURES=1 npx vitest run tests/integration/challenges/capstone-completion.test.ts
 */
const FIXTURE_DIR = join(process.cwd(), "tests/e2e/fixtures/capstones")
const PROOF_PATH = join(process.cwd(), "docs/quality-reports/capstone-completion-proof.md")
const GEN = !!process.env.GEN_CAPSTONE_FIXTURES

describe("Tier-6 absurd capstone completion proof (D71)", () => {
  beforeAll(async () => {
    mockComponentRepo.getAll.mockResolvedValue(loadLocalComponents())
    emptyRepo.getAll.mockResolvedValue([])
    await componentLibrary.initialize()
  })

  const capstones = getAllChallenges()
    .filter((c) => c.tier === 6)
    .sort((a, b) => a.id.localeCompare(b.id))
  const proofRows: string[] = []

  it("ships exactly 6 tier-6 capstones", () => {
    expect(capstones.length).toBe(6)
  })

  for (const c of capstones) {
    it(`"${c.id}" is completable within the UI budget (≤20 replicas/node)`, () => {
      const built = buildClearingSolution(c, MAX_REPLICAS)
      const cappedNodes = built.nodes
      const { breakdown, stats, maxReplica } = scoreSolution(c, { replicaCap: MAX_REPLICAS })

      expect(
        breakdown.stars,
        `${c.id}: stars=${breakdown.stars} underBudget=${breakdown.underBudget} cleanTopology=${breakdown.cleanTopology} ` +
          `maxReplica=${maxReplica}/${MAX_REPLICAS} ` +
          `uptime=${stats.uptimePercent.toFixed(1)}/${c.targetMetrics.uptimePercent} ` +
          `p99=${Math.round(stats.p99LatencyMs)}/${c.targetMetrics.p99LatencyMs}`,
      ).toBe(3)
      expect(maxReplica).toBeLessThanOrEqual(MAX_REPLICAS)
      expect(cappedNodes.length).toBeLessThanOrEqual(50)

      const peak = challengeCurve(c).reduce((m, p) => Math.max(m, p.rps), 0)
      proofRows.push(
        `| \`${c.id}\` | ${(peak / 1e6).toFixed(2)}M | ${breakdown.stars}★ | ` +
          `${stats.uptimePercent.toFixed(1)}% / ${c.targetMetrics.uptimePercent}% | ` +
          `${Math.round(stats.p99LatencyMs)} / ${c.targetMetrics.p99LatencyMs}ms | ` +
          `${cappedNodes.length} nodes, ≤${maxReplica} replicas |`,
      )

      if (GEN) {
        mkdirSync(FIXTURE_DIR, { recursive: true })
        writeFileSync(join(FIXTURE_DIR, `${c.id}.architecture.yaml`), dump(toArchitectureFixture(c, cappedNodes, built.edges)))
      }
    })
  }

  it("emits the proof report when GEN_CAPSTONE_FIXTURES is set", () => {
    if (!GEN) return
    const report = [
      "# Tier-6 Absurd Capstone Completion Proof",
      "",
      "> Generated by `tests/integration/challenges/capstone-completion.test.ts` (D71).",
      "> Each capstone is cleared by a reference architecture built within the UI's real budget",
      "> (≤50 nodes, ≤20 replicas/node) and scored through the production sim + rubric. The capstone",
      "> E2E (`tests/e2e/capstone-completion.spec.ts`) imports these same fixtures and screenshots a",
      "> passing result in the real app.",
      "",
      "| Capstone | Peak RPS | Stars | Uptime (got/target) | p99 (got/target) | Build |",
      "|----------|----------|-------|---------------------|------------------|-------|",
      ...proofRows,
      "",
      `_All ${proofRows.length} capstones clear the maximum 3★ within the buildable budget (≤50 nodes, ≤20 replicas). Fixtures: \`tests/e2e/fixtures/capstones/*.architecture.yaml\`._`,
      "",
    ].join("\n")
    mkdirSync(join(process.cwd(), "docs/quality-reports"), { recursive: true })
    writeFileSync(PROOF_PATH, report)
  })
})
