/**
 * Build-time generator for the offline Iconify `logos` subset.
 *
 * Importing `@iconify-json/logos` at runtime would inline the entire ~7.4 MB icon set into the
 * bundle (it ships one monolithic icons.json with no per-icon entry point). Instead we trim it at
 * build time to only the logos referenced by VENDOR_LOGOS, and emit a tiny generated module that
 * the app registers via `addCollection` (see src/icons/registry.ts).
 *
 * Run: `npm run gen:icons`. The output (src/icons/logos.generated.ts) IS committed; the lockstep
 * unit test guards against the map and the generated subset drifting apart.
 */
import { writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { icons as logos } from "@iconify-json/logos"
import { getIcons } from "@iconify/utils"
import { USED_LOGO_NAMES } from "../src/icons/officialIconMap.ts"

const subset = getIcons(logos, [...USED_LOGO_NAMES], true) // 3rd arg → populate subset.not_found
if (!subset) throw new Error("[gen-logos] getIcons returned null — check icon names in officialIconMap.ts")

const bundled = Object.keys(subset.icons ?? {}).sort()
const missing = subset.not_found ?? []
if (missing.length > 0) {
  console.warn(`[gen-logos] ⚠ ${missing.length} name(s) not in the logos set (these fall back to Lucide): ${missing.join(", ")}`)
}
console.log(`[gen-logos] bundled ${bundled.length}/${USED_LOGO_NAMES.length} logo(s)`)

// Stable, sorted output so regeneration is deterministic (no spurious git diffs in CI).
const sortedIcons: Record<string, unknown> = {}
for (const name of bundled) sortedIcons[name] = subset.icons[name]
const stable = { ...subset, icons: sortedIcons, not_found: undefined }

const outPath = resolve(dirname(fileURLToPath(import.meta.url)), "../src/icons/logos.generated.ts")
const contents =
  `// AUTO-GENERATED by scripts/gen-logos.mts — do not edit by hand. Run \`npm run gen:icons\`.\n` +
  `import type { IconifyJSON } from "@iconify/types"\n\n` +
  `export const logosSubset: IconifyJSON = ${JSON.stringify(stable)}\n`

writeFileSync(outPath, contents)
console.log(`[gen-logos] wrote ${outPath}`)
